# Introduction to Numpy

### Library Import

In [1]:
import numpy as np

### Array, Vector, Tensor ...

In [2]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [3]:
# Create an array with 3 elements, starting from default number 0.
b = np.arange(3)
print(b)

[0 1 2]


In [4]:
# Create an array that starts from integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
# Default type for values in the numpy function is a floating point (np.float64)
lin_spaced_arr = np.linspace(0, 100, 3)
print(lin_spaced_arr)

[  0.  50. 100.]


In [12]:
# Default type for values in the numpy function is a floating point (np.float64)
lin_spaced_arr = np.linspace(0, 100, 3, dtype=int)
print(lin_spaced_arr)

[  0  50 100]


- `numpy.ones()` - Returns a new array setting values to one.
- `numpy.zeros()` - Returns a new array setting values to zero.
- `numpy.empty()` - Returns a new uninitialized array. 
- `numpy.random.rand()` - Returns a new array with values chosen at random.

In [13]:
# Return a new array with 3 elements of 1. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [14]:
# Return a new array with 3 elements of 0.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [15]:
# Return a new array with 3 elements without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [16]:
# Return a new array with 3 elements between 0 and 1 chosen at random.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.26697212 0.76481155 0.40746452]


In [18]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [25]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multi-dimensional array using reshape()
# reshape(orginal_arr, dimension)

multi_dim_arr = np.reshape(one_dim_arr,(2,3))

# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [24]:

# Dimension of the 2-D array multi_dim_arr
print(multi_dim_arr.ndim)

2


In [26]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [27]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

### Vector math operations

In [28]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays element by element
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### Broadcasting

In [29]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

### Indexing

In [30]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [32]:
# Indexing on a 2-D array
two_dim = np.array((
          [1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


In [33]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Slicing

In [39]:
a

[1, 2, 3, 4, 5]

In [34]:
# Slice the array a to give the output [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [40]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# Slice the two_dim array to output the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# Similarily, slice the multi-dimensional array two_dim to output the last two rows
sliced_two_dim_rows = two_dim[1:4]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [45]:
print(type(sliced_arr_1))
print(type(sliced_two_dim_rows))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [43]:
# accessing the second column
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


### Stacking

Stacking is a feature of NumPy that leads to increased customization of arrays. It basically means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis. 

- `vstack` - stacks vertically
- `hstack` - stacks horizontally
- `hsplit` - splits an array into several smaller arrays

In [46]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [48]:
# Stack arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [49]:
# Stack arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


## Linear Systems with Matrices

Let's solve this equation ...

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}$$

In [53]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Vector b:
[7. 1.]


In [54]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [-1.  2.]


In [55]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


How about singular matrix ...

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1-9x_2=1, \end{cases}$$

In [56]:
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [60]:
# x_2 = np.linalg.solve(A_2, b_2)

In [57]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


***Three*** unknown ***Three*** equations

$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}$$

In [62]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Vector b:
[-10.   0.  17.]


In [63]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


### Dot Product

In [64]:
x = [1, -2, -5]
y = [4, 3, -1]

In [65]:
def dot(x, y):
    s=0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

In [66]:
print("The dot product of x and y is", dot(x, y))

The dot product of x and y is 3


In [67]:
print("np.dot(x,y) function returns dot product of x and y:", np.dot(x, y)) 

np.dot(x,y) function returns dot product of x and y: 3


In [68]:
print("This line output is a dot product of x and y: ", np.array(x) @ np.array(y))

print("\nThis line output is an error:")
try:
    print(x @ y)
except TypeError as err:
    print(err)

This line output is a dot product of x and y:  3

This line output is an error:
unsupported operand type(s) for @: 'list' and 'list'


### Matrix multiplication

In [71]:
A = np.array(
    [[4, 9, 9], 
     [9, 1, 6], 
     [9, 2, 3]])
print("Matrix A (3 x 3):\n", A)

B = np.array(
    [[2, 2], 
     [5, 7], 
     [4, 4]])
print("Matrix B (3 x 2):\n", B)

Matrix A (3 x 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 x 2):
 [[2 2]
 [5 7]
 [4 4]]


In [70]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [72]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])